spring:
  application:
    name: UBERSOCKETSERVER
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: sample-group
      auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://mysql:3306/uber_db_local?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "sahil#123"
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

server:
  port: 7779

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
