spring:
  kafka:
    bootstrap-servers: 172.24.65.33:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: sample-group
      auto-offset-reset: earliest

  application:
    name: UberSocketServer
  main:
    allow-bean-definition-overriding: true

server:
  port: 7779

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    preferIpAddress: true
