plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
    mavenLocal()
}
configurations.all {
    resolutionStrategy {
        // Force a kafka-clients version compatible with Spring Boot 3.x / Spring 6.1.x
        force 'org.apache.kafka:kafka-clients:3.6.1'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.example:UberProject-EntityService:0.0.8-SNAPSHOT'
// Flyway runtime dependencies for Spring Boot 3 + MySQL
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.1.1'

// Source: https://mvnrepository.com/artifact/org.springframework.kafka/spring-kafka
    implementation 'org.springframework.kafka:spring-kafka'
    
}

tasks.named('test') {
    useJUnitPlatform()
}
