server:
  port: 7477

spring:
  application:
    name: UberBookingService
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/uber_db_local
    username: root
    password: "sahil#123"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
