server:
  port: 7477

spring:
  application:
    name: UberBookingService
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/Uber_Db_Local
    username: root
    password: "sahil#123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
